services:
  - type: web
    name: olx-scraper
    env: docker
    plan: free
    region: frankfurt
    repo: https://github.com/gnez360/olx-scrapper.git
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
